name: 'Coverage Reporter'
description: 'Coverage Reporter'

inputs:
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: false
  pull-number:
    required: true
    description: 'Pull Request Number'
  repository: 
    required: true
    description: 'Repository Name'
  head-branch:
    required: true
    description: 'Head Branch'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pull-number }}
    - ${{ inputs.repository }}
    - ${{ inputs.head-branch }}
    - ${{ inputs.GITHUB_TOKEN }}
