name: Main

on:
  push:
    branches:
      - master
env:
  MIX_ENV: prod
  ELIXIR_VERSION: 1.16.1-otp-26
  OTP_VERSION: 26.2.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Install Mix Dependencies
        run: mix deps.get

      - name: Escript Build
        run: mix escript.build

      - name: Commit Coverage Reporter Binary
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: "coverage_reporter"
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "[auto-commit] Update coverage_reporter binary"
